name: testing yaml 

#1 - atomated workflow (observe cron syntax)
#on:
#  schedule:
#    -cron: '0 * * * *' #meaning we workflow runs every hour

#2 - manual workflow
#on:
#  workflow_dispatch: #we trigger the workflow to occur in the github repo

#3 - workflow through HTTP request
#on:
#  repository_dispatch:
#    types: event_type #need to send POST request to github API and triggers repo
#dispatch event executing workflow based on event_type

#choosing virtual machine
#jobs:
#  on:
#    runs-on: ubuntu-latest

#runnings jobs

on: push #when i push to github activate code


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install ruff
    - run: |
      ruff check .
      ruff fix .
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style fixes by ruff'